"""Durable local policy graph with a single lock, leases, and fences."""

from __future__ import annotations

from contextlib import contextmanager
from datetime import datetime, timedelta, timezone
import fcntl
import json
import os
from pathlib import Path
import secrets
from types import MappingProxyType
from typing import Iterable, Iterator, Mapping, TypeGuard
import unicodedata
from urllib.parse import urlsplit

MAX_GOAL_BYTES = 4096
MAX_RESULT_BYTES = 2048
MAX_REFERENCES = 4
MAX_REFERENCE_BYTES = 2048
MAX_QUESTION_BYTES = 2048
MAX_ANSWER_BYTES = 2048
MAX_ORIGIN_REF_BYTES = 256
MAX_CONSULTATION_SECONDS = 86400
LEASE_SECONDS = 900
_TASK_PREFIX = "task_"
_LEASE_PREFIX = "lease_"
_CONSULTATION_PREFIX = "consultation_"
_ROUTE_MODES = frozenset(("task", "consultation"))


class QueueRefused(ValueError):
    """Stable, content-free refusal for untrusted input or stale state."""

    def __init__(self) -> None:
        super().__init__("request refused")


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _stamp(value: datetime) -> str:
    return value.astimezone(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _instant(value: datetime | None) -> datetime:
    if value is None:
        return _now()
    if not isinstance(value, datetime) or value.utcoffset() is None:
        raise QueueRefused()
    return value.astimezone(timezone.utc)


def _parse_stamp(value: object) -> datetime:
    try:
        if not isinstance(value, str):
            raise ValueError
        parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
        if parsed.utcoffset() is None:
            raise ValueError
        return parsed.astimezone(timezone.utc)
    except (TypeError, ValueError) as exc:
        raise QueueRefused() from exc


def _public_https(value: str) -> bool:
    if not _safe_text(value, MAX_REFERENCE_BYTES):
        return False
    parsed = urlsplit(value)
    if parsed.scheme != "https" or not parsed.hostname or parsed.username or parsed.password or parsed.fragment:
        return False
    host = parsed.hostname.rstrip(".").lower()
    if host == "localhost" or host.endswith(".local"):
        return False
    # Numeric address literals, including private ranges, are intentionally not accepted.
    return any(character.isalpha() for character in host) and "." in host


def _safe_text(value: object, maximum_bytes: int) -> bool:
    """Bound text and refuse control characters except ordinary layout whitespace."""
    if not isinstance(value, str) or not value or len(value.encode()) > maximum_bytes:
        return False
    return all(character in "\n\r\t" or not unicodedata.category(character).startswith("C") for character in value)


def _identifier(value: str, prefix: str) -> bool:
    """Accept only IDs generated by this module, never filesystem syntax."""
    suffix = value.removeprefix(prefix)
    return value.startswith(prefix) and len(suffix) == 32 and all(char in "0123456789abcdef" for char in suffix)


def _identity(value: object) -> TypeGuard[str]:
    """Closed, portable identity syntax; authorization is configured locally."""
    return (
        type(value) is str
        and 1 <= len(value) <= 64
        and all(char in "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-" for char in value)
    )


class RoutePolicy:
    """Immutable local authority graph for directional agent routes."""

    __slots__ = ("agents", "routes", "_frozen")

    def __setattr__(self, name: str, value: object) -> None:
        if getattr(self, "_frozen", False):
            raise AttributeError("RoutePolicy is immutable")
        object.__setattr__(self, name, value)

    def __delattr__(self, name: str) -> None:
        raise AttributeError("RoutePolicy is immutable")

    def __init__(
        self,
        *,
        agents: Iterable[str],
        routes: Mapping[tuple[str, str], Iterable[str]],
    ) -> None:
        try:
            configured_agents = frozenset(agents)
        except TypeError as exc:
            raise QueueRefused() from exc
        if (
            not configured_agents
            or not all(_identity(agent) for agent in configured_agents)
            or not isinstance(routes, Mapping)
            or not routes
        ):
            raise QueueRefused()
        configured_routes: dict[tuple[str, str], frozenset[str]] = {}
        for edge, modes in routes.items():
            try:
                source, destination = edge
                allowed_modes = frozenset(modes)
            except (TypeError, ValueError) as exc:
                raise QueueRefused() from exc
            if (
                not isinstance(edge, tuple)
                or len(edge) != 2
                or source not in configured_agents
                or destination not in configured_agents
                or not allowed_modes
                or not allowed_modes <= _ROUTE_MODES
            ):
                raise QueueRefused()
            configured_routes[(source, destination)] = allowed_modes
        self.agents = configured_agents
        self.routes = MappingProxyType(configured_routes)
        self._frozen = True

    def allows(self, source: str, destination: str, mode: str) -> bool:
        return mode in self.routes.get((source, destination), ())

    def destinations(self, source: str, mode: str) -> tuple[str, ...]:
        return tuple(
            sorted(
                destination
                for (route_source, destination), modes in self.routes.items()
                if route_source == source and mode in modes
            )
        )

    def as_record(self) -> dict:
        return {
            "agents": sorted(self.agents),
            "routes": [
                {"source": source, "destination": destination, "modes": sorted(modes)}
                for (source, destination), modes in sorted(self.routes.items())
            ],
        }


class DurableQueue:
    """A filesystem-backed queue. Every state transition is serialized by one lock."""

    def __init__(
        self,
        root: Path,
        *,
        policy: RoutePolicy | None = None,
        agent_id: str | None = None,
        producer_id: str | None = None,
        worker_id: str | None = None,
    ) -> None:
        self._legacy_pair = policy is None
        if policy is None:
            if agent_id is not None or producer_id is None or worker_id is None:
                raise QueueRefused()
            producer = producer_id
            worker = worker_id
            if not _identity(producer) or not _identity(worker):
                raise QueueRefused()
            policy = RoutePolicy(
                agents=(producer, worker),
                routes={(producer, worker): _ROUTE_MODES},
            )
            self._source_id, self._worker_id = producer, worker
        else:
            if (
                not isinstance(policy, RoutePolicy)
                or not _identity(agent_id)
                or agent_id not in policy.agents
                or producer_id is not None
                or worker_id is not None
            ):
                raise QueueRefused()
            self._source_id = self._worker_id = agent_id
        self.root = Path(root)
        self.policy = policy
        self.agent_id = agent_id
        self.producer_id, self.worker_id = self._source_id, self._worker_id
        self.root.mkdir(parents=True, exist_ok=True, mode=0o700)
        os.chmod(self.root, 0o700)
        (self.root / "tasks").mkdir(exist_ok=True, mode=0o700)
        (self.root / "idempotency").mkdir(exist_ok=True, mode=0o700)
        (self.root / "consultations").mkdir(exist_ok=True, mode=0o700)
        (self.root / "consultation_idempotency").mkdir(exist_ok=True, mode=0o700)
        self._lock_path = self.root / ".queue.lock"
        with self._locked():
            policy_path = self.root / "policy.json"
            if policy_path.exists():
                if self._read(policy_path) != self.policy.as_record():
                    raise QueueRefused()
            else:
                for records, mode in (
                    (self._tasks(), "task"),
                    (self._consultations(), "consultation"),
                ):
                    for record in records:
                        source = record.get("producer_id")
                        destination = record.get("worker_id")
                        if (
                            not _identity(source)
                            or not _identity(destination)
                            or not self.policy.allows(source, destination, mode)
                        ):
                            raise QueueRefused()
                self._write(policy_path, self.policy.as_record())

    @contextmanager
    def _locked(self) -> Iterator[None]:
        with self._lock_path.open("a+", encoding="utf-8") as handle:
            fcntl.flock(handle.fileno(), fcntl.LOCK_EX)
            try:
                yield
            finally:
                fcntl.flock(handle.fileno(), fcntl.LOCK_UN)

    def _path(self, task_id: str) -> Path:
        return self.root / "tasks" / f"{task_id}.json"

    def _destination(self, destination_id: str | None, mode: str) -> str:
        destinations = self.policy.destinations(self._source_id, mode)
        destination = destinations[0] if destination_id is None and len(destinations) == 1 else destination_id
        if (
            not isinstance(destination, str)
            or not _identity(destination)
            or not self.policy.allows(self._source_id, destination, mode)
        ):
            raise QueueRefused()
        return destination

    def _idempotency_path(self, directory: str, destination: str, key: str) -> Path:
        namespace = self.root / directory / self._source_id / destination
        namespace.mkdir(parents=True, exist_ok=True, mode=0o700)
        return namespace / key

    def _consultation_path(self, consultation_id: str) -> Path:
        return self.root / "consultations" / f"{consultation_id}.json"

    def _write(self, path: Path, value: dict) -> None:
        temporary = path.with_name(f".{path.name}.{secrets.token_hex(8)}.tmp")
        with temporary.open("x", encoding="utf-8") as handle:
            json.dump(value, handle, separators=(",", ":"), ensure_ascii=True)
            handle.flush()
            os.fsync(handle.fileno())
        temporary.replace(path)
        directory_fd = os.open(path.parent, os.O_RDONLY)
        try:
            os.fsync(directory_fd)
        finally:
            os.close(directory_fd)

    @staticmethod
    def _read(path: Path) -> dict:
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError, TypeError) as exc:
            raise QueueRefused() from exc

    def enqueue(
        self,
        *,
        goal: str,
        references: list[str],
        idempotency_key: str,
        destination_id: str | None = None,
    ) -> str:
        producer = self._source_id
        destination = self._destination(destination_id, "task")
        if (not _safe_text(goal, MAX_GOAL_BYTES) or
                not isinstance(references, list) or len(references) > MAX_REFERENCES or
                not all(isinstance(item, str) and _public_https(item) for item in references) or
                not isinstance(idempotency_key, str) or idempotency_key in (".", "..") or not idempotency_key or len(idempotency_key) > 160):
            raise QueueRefused()
        with self._locked():
            if not all(char.isalnum() or char in "._-" for char in idempotency_key):
                raise QueueRefused()
            key_path = self._idempotency_path("idempotency", destination, idempotency_key)
            legacy_key_path = self.root / "idempotency" / idempotency_key
            if self._legacy_pair and legacy_key_path.exists():
                return str(self._read(legacy_key_path)["task_id"])
            if key_path.exists():
                return str(self._read(key_path)["task_id"])
            task_id = f"{_TASK_PREFIX}{secrets.token_hex(16)}"
            task = {"task_id": task_id, "producer_id": producer, "worker_id": destination, "goal": goal, "references": references, "status": "pending", "lease_id": None, "lease_expires_at": None, "result": None}
            self._write(self._path(task_id), task)
            self._write(key_path, {"task_id": task_id})
            return task_id

    def ask_question(
        self,
        *,
        question: str,
        origin_ref: str,
        idempotency_key: str,
        expires_in_seconds: int,
        destination_id: str | None = None,
        now: datetime | None = None,
    ) -> dict:
        """Create an advice-only consultation from the configured local producer."""
        producer = self._source_id
        destination = self._destination(destination_id, "consultation")
        if (
            not _safe_text(question, MAX_QUESTION_BYTES)
            or not _safe_text(origin_ref, MAX_ORIGIN_REF_BYTES)
            or not isinstance(idempotency_key, str)
            or idempotency_key in ("", ".", "..")
            or len(idempotency_key) > 160
            or not all(char.isalnum() or char in "._-" for char in idempotency_key)
            or not isinstance(expires_in_seconds, int)
            or isinstance(expires_in_seconds, bool)
            or not 1 <= expires_in_seconds <= MAX_CONSULTATION_SECONDS
        ):
            raise QueueRefused()
        instant = _instant(now)
        with self._locked():
            key_path = self._idempotency_path(
                "consultation_idempotency", destination, idempotency_key
            )
            legacy_key_path = self.root / "consultation_idempotency" / idempotency_key
            if self._legacy_pair and legacy_key_path.exists():
                existing_id = self._read(legacy_key_path)["consultation_id"]
                return self._read(self._consultation_path(existing_id))
            if key_path.exists():
                existing_id = self._read(key_path)["consultation_id"]
                return self._read(self._consultation_path(existing_id))
            consultation_id = f"{_CONSULTATION_PREFIX}{secrets.token_hex(16)}"
            record = {
                "consultation_id": consultation_id,
                "producer_id": producer,
                "worker_id": destination,
                "origin_ref": origin_ref,
                "idempotency_key": idempotency_key,
                "question": question,
                "status": "pending",
                "created_at": _stamp(instant),
                "expires_at": _stamp(instant + timedelta(seconds=expires_in_seconds)),
                "lease_id": None,
                "lease_expires_at": None,
                "claimed_at": None,
                "answer": None,
                "answered_at": None,
            }
            self._write(self._consultation_path(consultation_id), record)
            self._write(key_path, {"consultation_id": consultation_id})
            return record

    def read_answer(
        self,
        consultation_id: str,
        *,
        now: datetime | None = None,
    ) -> dict:
        """Read consultation state through the configured local producer route."""
        producer = self._source_id
        if (
            not isinstance(consultation_id, str)
            or not _identifier(consultation_id, _CONSULTATION_PREFIX)
        ):
            raise QueueRefused()
        instant = _instant(now)
        with self._locked():
            record = self._read(self._consultation_path(consultation_id))
            if record.get("producer_id") != producer:
                raise QueueRefused()
            if record.get("status") in ("pending", "leased") and _parse_stamp(record.get("expires_at")) <= instant:
                record["status"] = "expired"
                self._write(self._consultation_path(consultation_id), record)
            return record

    def _consultations(self) -> list[dict]:
        return [
            self._read(path)
            for path in sorted((self.root / "consultations").glob("consultation_*.json"))
        ]

    def claim_question(
        self,
        now: datetime | None = None,
    ) -> dict | None:
        """Claim one pending or expired-lease consultation for the configured worker."""
        worker = self._worker_id
        instant = _instant(now)
        with self._locked():
            for record in self._consultations():
                if record.get("worker_id") != worker:
                    continue
                expires_at = _parse_stamp(record.get("expires_at"))
                if record.get("status") in ("pending", "leased") and expires_at <= instant:
                    record["status"] = "expired"
                    self._write(self._consultation_path(record["consultation_id"]), record)
                    continue
                lease_expired = (
                    record.get("status") == "leased"
                    and _parse_stamp(record.get("lease_expires_at")) <= instant
                )
                if record.get("status") != "pending" and not lease_expired:
                    continue
                record["status"] = "leased"
                record["lease_id"] = f"{_LEASE_PREFIX}{secrets.token_hex(16)}"
                record["lease_expires_at"] = _stamp(
                    min(instant + timedelta(seconds=LEASE_SECONDS), expires_at)
                )
                record["claimed_at"] = _stamp(instant)
                self._write(self._consultation_path(record["consultation_id"]), record)
                return {
                    key: record[key]
                    for key in (
                        "consultation_id",
                        "origin_ref",
                        "question",
                        "expires_at",
                        "lease_id",
                        "lease_expires_at",
                    )
                }
        return None

    def answer_question(
        self,
        *,
        consultation_id: str,
        lease_id: str,
        answer: str,
        now: datetime | None = None,
    ) -> str:
        """Store a bounded answer for a claimed consultation."""
        worker = self._worker_id
        if (
            not isinstance(consultation_id, str)
            or not _identifier(consultation_id, _CONSULTATION_PREFIX)
            or not isinstance(lease_id, str)
            or not _identifier(lease_id, _LEASE_PREFIX)
            or not _safe_text(answer, MAX_ANSWER_BYTES)
        ):
            raise QueueRefused()
        instant = _instant(now)
        with self._locked():
            record = self._read(self._consultation_path(consultation_id))
            expires_at = _parse_stamp(record.get("expires_at"))
            if expires_at <= instant and record.get("status") in ("pending", "leased"):
                record["status"] = "expired"
                self._write(self._consultation_path(consultation_id), record)
                raise QueueRefused()
            if (
                record.get("worker_id") != worker
                or record.get("status") != "leased"
                or record.get("lease_id") != lease_id
                or _parse_stamp(record.get("lease_expires_at")) <= instant
            ):
                raise QueueRefused()
            record["status"] = "answered"
            record["answer"] = answer
            record["answered_at"] = _stamp(instant)
            self._write(self._consultation_path(consultation_id), record)
            return "answered"

    def _tasks(self) -> list[dict]:
        return [self._read(path) for path in sorted((self.root / "tasks").glob("task_*.json"))]

    def claim(self, now: datetime | None = None) -> dict | None:
        worker = self._worker_id
        instant = now or _now()
        with self._locked():
            for task in self._tasks():
                if task.get("worker_id") != worker:
                    continue
                expired = task["status"] == "leased" and datetime.fromisoformat(task["lease_expires_at"].replace("Z", "+00:00")) <= instant
                if task["status"] not in ("pending",) and not expired:
                    continue
                task["status"] = "leased"
                task["lease_id"] = f"{_LEASE_PREFIX}{secrets.token_hex(16)}"
                task["lease_expires_at"] = _stamp(instant + timedelta(seconds=LEASE_SECONDS))
                self._write(self._path(task["task_id"]), task)
                return {key: task[key] for key in ("task_id", "goal", "references", "lease_id", "lease_expires_at")}
        return None

    def finish(self, *, task_id: str, lease_id: str, result: str | None, failed: bool, now: datetime | None = None) -> str:
        worker = self._worker_id
        if (not isinstance(task_id, str) or not isinstance(lease_id, str) or
                not _identifier(task_id, _TASK_PREFIX) or not _identifier(lease_id, _LEASE_PREFIX)):
            raise QueueRefused()
        if not failed and not _safe_text(result, MAX_RESULT_BYTES):
            raise QueueRefused()
        with self._locked():
            task = self._read(self._path(task_id))
            if task.get("worker_id") != worker:
                raise QueueRefused()
            if task["status"] in ("completed", "failed"):
                if task["lease_id"] == lease_id:
                    return f"already_{task['status']}"
                raise QueueRefused()
            instant = now or _now()
            if task["status"] != "leased" or task["lease_id"] != lease_id or datetime.fromisoformat(task["lease_expires_at"].replace("Z", "+00:00")) <= instant:
                raise QueueRefused()
            task["status"] = "failed" if failed else "completed"
            task["result"] = None if failed else result
            self._write(self._path(task_id), task)
            return task["status"]

    def read_task(self, task_id: str) -> dict:
        if not isinstance(task_id, str) or not _identifier(task_id, _TASK_PREFIX):
            raise QueueRefused()
        with self._locked():
            task = self._read(self._path(task_id))
            if task.get("producer_id") != self._source_id:
                raise QueueRefused()
            return task

    def inspect(self, task_id: str) -> dict:
        return self.read_task(task_id)
