"""Durable local queue with a single lock, leases, and completion fences."""

from __future__ import annotations

from contextlib import contextmanager
from datetime import datetime, timedelta, timezone
import fcntl
import json
import os
from pathlib import Path
import secrets
from typing import Iterator
import unicodedata
from urllib.parse import urlsplit

MAX_GOAL_BYTES = 4096
MAX_RESULT_BYTES = 2048
MAX_REFERENCES = 4
MAX_REFERENCE_BYTES = 2048
LEASE_SECONDS = 900
_TASK_PREFIX = "task_"
_LEASE_PREFIX = "lease_"


class QueueRefused(ValueError):
    """Stable, content-free refusal for untrusted input or stale state."""

    def __init__(self) -> None:
        super().__init__("request refused")


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _stamp(value: datetime) -> str:
    return value.astimezone(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _public_https(value: str) -> bool:
    if not _safe_text(value, MAX_REFERENCE_BYTES):
        return False
    parsed = urlsplit(value)
    if parsed.scheme != "https" or not parsed.hostname or parsed.username or parsed.password or parsed.fragment:
        return False
    host = parsed.hostname.rstrip(".").lower()
    if host == "localhost" or host.endswith(".local"):
        return False
    # Numeric address literals, including private ranges, are intentionally not accepted.
    return any(character.isalpha() for character in host) and "." in host


def _safe_text(value: object, maximum_bytes: int) -> bool:
    """Bound text and refuse control characters except ordinary layout whitespace."""
    if not isinstance(value, str) or not value or len(value.encode()) > maximum_bytes:
        return False
    return all(character in "\n\r\t" or not unicodedata.category(character).startswith("C") for character in value)


def _identifier(value: str, prefix: str) -> bool:
    """Accept only IDs generated by this module, never filesystem syntax."""
    suffix = value.removeprefix(prefix)
    return value.startswith(prefix) and len(suffix) == 32 and all(char in "0123456789abcdef" for char in suffix)


def _identity(value: str) -> bool:
    """Closed, portable identity syntax; authorization is configured locally."""
    return isinstance(value, str) and 1 <= len(value) <= 64 and all(char.isalnum() or char in "_-" for char in value)


class DurableQueue:
    """A filesystem-backed queue. Every state transition is serialized by one lock."""

    def __init__(self, root: Path, *, producer_id: str = "producer", worker_id: str = "worker") -> None:
        if not _identity(producer_id) or not _identity(worker_id):
            raise QueueRefused()
        self.root = Path(root)
        self.producer_id, self.worker_id = producer_id, worker_id
        self.root.mkdir(parents=True, exist_ok=True, mode=0o700)
        os.chmod(self.root, 0o700)
        (self.root / "tasks").mkdir(exist_ok=True, mode=0o700)
        (self.root / "idempotency").mkdir(exist_ok=True, mode=0o700)
        self._lock_path = self.root / ".queue.lock"

    @contextmanager
    def _locked(self) -> Iterator[None]:
        with self._lock_path.open("a+", encoding="utf-8") as handle:
            fcntl.flock(handle.fileno(), fcntl.LOCK_EX)
            try:
                yield
            finally:
                fcntl.flock(handle.fileno(), fcntl.LOCK_UN)

    def _path(self, task_id: str) -> Path:
        return self.root / "tasks" / f"{task_id}.json"

    def _write(self, path: Path, value: dict) -> None:
        temporary = path.with_name(f".{path.name}.{secrets.token_hex(8)}.tmp")
        with temporary.open("x", encoding="utf-8") as handle:
            json.dump(value, handle, separators=(",", ":"), ensure_ascii=True)
            handle.flush()
            os.fsync(handle.fileno())
        temporary.replace(path)
        directory_fd = os.open(path.parent, os.O_RDONLY)
        try:
            os.fsync(directory_fd)
        finally:
            os.close(directory_fd)

    @staticmethod
    def _read(path: Path) -> dict:
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError, TypeError) as exc:
            raise QueueRefused() from exc

    def enqueue(self, *, goal: str, references: list[str], idempotency_key: str, producer_id: str | None = None) -> str:
        producer = self.producer_id if producer_id is None else producer_id
        if (not _safe_text(goal, MAX_GOAL_BYTES) or
                not isinstance(references, list) or len(references) > MAX_REFERENCES or
                not all(isinstance(item, str) and _public_https(item) for item in references) or
                not isinstance(idempotency_key, str) or idempotency_key in (".", "..") or not idempotency_key or len(idempotency_key) > 160 or
                producer != self.producer_id):
            raise QueueRefused()
        with self._locked():
            if not all(char.isalnum() or char in "._-" for char in idempotency_key):
                raise QueueRefused()
            key_path = self.root / "idempotency" / idempotency_key
            if key_path.exists():
                return str(self._read(key_path)["task_id"])
            task_id = f"{_TASK_PREFIX}{secrets.token_hex(16)}"
            task = {"task_id": task_id, "producer_id": producer, "worker_id": self.worker_id, "goal": goal, "references": references, "status": "pending", "lease_id": None, "lease_expires_at": None, "result": None}
            self._write(self._path(task_id), task)
            self._write(key_path, {"task_id": task_id})
            return task_id

    def _tasks(self) -> list[dict]:
        return [self._read(path) for path in sorted((self.root / "tasks").glob("task_*.json"))]

    def claim(self, now: datetime | None = None, *, worker_id: str | None = None) -> dict | None:
        worker = self.worker_id if worker_id is None else worker_id
        if worker != self.worker_id:
            raise QueueRefused()
        instant = now or _now()
        with self._locked():
            for task in self._tasks():
                expired = task["status"] == "leased" and datetime.fromisoformat(task["lease_expires_at"].replace("Z", "+00:00")) <= instant
                if task["status"] not in ("pending",) and not expired:
                    continue
                task["status"] = "leased"
                task["lease_id"] = f"{_LEASE_PREFIX}{secrets.token_hex(16)}"
                task["lease_expires_at"] = _stamp(instant + timedelta(seconds=LEASE_SECONDS))
                self._write(self._path(task["task_id"]), task)
                return {key: task[key] for key in ("task_id", "goal", "references", "lease_id", "lease_expires_at")}
        return None

    def finish(self, *, task_id: str, lease_id: str, result: str | None, failed: bool, now: datetime | None = None, worker_id: str | None = None) -> str:
        worker = self.worker_id if worker_id is None else worker_id
        if (not isinstance(task_id, str) or not isinstance(lease_id, str) or
                not _identifier(task_id, _TASK_PREFIX) or not _identifier(lease_id, _LEASE_PREFIX) or worker != self.worker_id):
            raise QueueRefused()
        if not failed and not _safe_text(result, MAX_RESULT_BYTES):
            raise QueueRefused()
        with self._locked():
            task = self._read(self._path(task_id))
            if task["status"] in ("completed", "failed"):
                if task["lease_id"] == lease_id:
                    return f"already_{task['status']}"
                raise QueueRefused()
            instant = now or _now()
            if task["worker_id"] != worker or task["status"] != "leased" or task["lease_id"] != lease_id or datetime.fromisoformat(task["lease_expires_at"].replace("Z", "+00:00")) <= instant:
                raise QueueRefused()
            task["status"] = "failed" if failed else "completed"
            task["result"] = None if failed else result
            self._write(self._path(task_id), task)
            return task["status"]

    def inspect(self, task_id: str) -> dict:
        with self._locked():
            return self._read(self._path(task_id))
